import TripPlannerForm from '../components/TripPlannerForm';
import HeroSection from '../components/HeroSection';
import FeaturesSection from '../components/FeaturesSection';
import type { Metadata } from "next";
import { SITE_NAME } from "../lib/seo";

// 👇 Add this to set the browser tab title and description
export const metadata: Metadata = {
  title: SITE_NAME,
  description:
    "Generate personalized, end-to-end travel itineraries in seconds—optimized daily schedules, attractions, and activities based on your preferences.",
  alternates: { canonical: "/" },
};

export default function Home() {
  return (
    <main className="min-h-screen bg-blue-100 ">
      <HeroSection />
      <FeaturesSection />

      <section id="planner" className="py-20 bg-blue-100">
        <div className="max-w-4xl mx-auto px-4">
          <h2 className="text-4xl font-bold text-center text-gray-900 mb-2">
            Plan Your Trip
          </h2>
          <p className="text-center text-gray-600 mb-8">
            Get a personalized trip itinerary generated by AI based on your preferences
          </p>
          <TripPlannerForm />
        </div>
      </section>
    </main>
  );
}
