import type { Metadata } from "next";
import { SITE_NAME, SITE_URL } from "../../lib/seo";

export const metadata: Metadata = {
  title: `Terms of Service | ${SITE_NAME}`,
  description: "Terms of service for AI Trip Planner.",
  alternates: { canonical: `${SITE_URL}/terms` },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-blue-100">
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">Terms of Service</h1>
          <p className="text-gray-700">
            {SITE_NAME} provides itinerary suggestions generated by AI. Use common sense and verify important details (hours, prices, safety, and local rules).
          </p>

          <h2 className="text-2xl font-semibold text-gray-900 mt-10 mb-3">No warranties</h2>
          <p className="text-gray-700">
            The service is provided “as is” without warranties. Travel conditions can change; you are responsible for decisions made using the output.
          </p>

          <h2 className="text-2xl font-semibold text-gray-900 mt-10 mb-3">Acceptable use</h2>
          <p className="text-gray-700">
            Do not attempt to abuse the service, scrape content at scale, or submit illegal or harmful content.
          </p>
        </div>
      </section>
    </main>
  );
}

